title: Intro to Pipelines
description: >-
  Get an introduction to data analysis pipelines as we use them in the USGS Data
  Science Branch
template:
  repo: ds-pipelines-1-template
  name: ds-pipelines-1
before:
  - type: createIssue
    title: Get started with USGS Data Science pipelines
    body: 00-overview.md
    store:
      overview_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Get the big picture
    description: Learn about our goals and general approaches for data analysis pipelines
    link: '{{ store.overview_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 01-install-activity.md
        store:
          install_activity_url: '{{ result.data.html_url }}'
  - title: Configure your R environment
    description: >-
      Install packages and establish an RStudio project for the exercises in the
      course
    link: '{{ store.install_activity_url }}'
    event: issue_comment.created
    actions:
      - type: gate
        left: USGS Support Package
        operator: test
        right: '%payload.comment.body%'
        else:
          - type: respond
            with: 01a-install-fail.md
      - type: respond
        with: 01b-install-success.md
      - type: closeIssue
      - type: createIssue
        title: Structure your code predictably
        body: 10-structure.md
        store:
          structure_issue_url: '{{ result.data.html_url }}'
          structure_issue_id: '{{ payload.issue.number }}'
  - title: Directory structure and code decomposition
    description: Learn about team conventions for we organize pipeline files and code
    link: '{{ store.structure_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: xx-goto-next-issue.md
        store:
          structure_activity_url: '{{ result.data.html_url }}'
  - title: Open a pull request for directory structure
    description: Begin to organize code files according our team conventions
    link: '{{ store.structure_activity_url }}'
    event: pull_request.opened
    actions:
      - type: createReview
        body: 12-function-activity.md
        event: REQUEST_CHANGES
        store:
          function_activity_url: '{{ result.data.html_url }}'
  - title: Modify your pull request with code decomposition
    description: Decompose code into functions
    link: '{{ store.structure_activity_url }}'
    event: pull_request.closed
    actions:
      - type: respond
        with: xx-goto-next-issue.md
      - type: closeIssue
        issue: '{{ store.structure_issue_id }}'
      - type: createIssue
        title: Why use a dependency manager?
        body: 20-why-dependency-management.md
        store:
          why_dependency_management_issue_url: '{{ result.data.html_url }}'
  - title: Why use a dependency manager?
    description: Read and watch about the benefits of formal dependency management
    link: '{{ store.why_dependency_management_issue_url }}'
    event: issues.closed
    actions:
      - type: createIssue
        title: The anatomy of a remakefile
        body: 30-makefile-anatomy.md
        store:
          makefile_anatomy_url: '{{ result.data.html_url }}'
  - title: The anatomy of a remakefile
    description: Learn how to declare the relationships among files in an analysis
    link: '{{ store.makefile_anatomy_url }}'
    event: issues.closed
    actions:
      - type: respond
        with: xx-goto-next-issue.md
      - type: createIssue
        title: Where to learn more
        body: 90-references.md
