title: ds-pipelines-1
description: Intro to Data Analysis Pipelines for USGS Data Science
template:
  repo: ds-pipelines-1-template
  name: ds-pipelines-1
before:
  - type: createIssue
    title: Get started with USGS Data Science pipelines
    body: 00-overview.md
    store:
      first_issue_url: '{{ result.data.html_url }}'
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
