title: Intro to Pipelines
description: Get an introduction to data analysis pipelines as we use them in the USGS Data Science Branch
template:
  repo: ds-pipelines-1-template
  name: ds-pipelines-1
before:
  - type: createIssue
    title: Get started with USGS Data Science pipelines
    body: 00-overview.md
    store:
      first_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Get the big picture
    description: Learn about our goals and general approaches for data analysis pipelines
    link: '{{ store.first_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 00-configure.md
        store:
          configure_comment_url: '{{ result.data.html_url }}'
